Get pdf-swap-edge to work for either pdftk or qpdf
This fixes an issue where there's no good installation of pdftk
available for Fedora.

Signed-off-by: Schuyler Eldridge <schuyler.eldridge@gmail.com>

diff --git a/home/usr/bin/pdf-swap-edge b/home/usr/bin/pdf-swap-edge
--- a/home/usr/bin/pdf-swap-edge
+++ b/home/usr/bin/pdf-swap-edge
@@ -1,4 +1,12 @@
 #!/bin/bash
 
 basename=${1%%.*}
-pdftk A=$basename.pdf shuffle AoddNorth AevenSouth output $basename-swapped.pdf
+
+if [ -x "$(command -v pdftk)" ]; then
+  pdftk A=$basename.pdf shuffle AoddNorth AevenSouth output $basename-swapped.pdf
+elif [ -x "$(command -v qpdf)" ]; then
+  qpdf --rotate=180:1-z:even $basename.pdf $basename-swapped.pdf
+else
+  echo "[error] Cannot find either 'pdftk' or 'qpdf' on the \$PATH" >&2
+  exit 1
+fi
